version: "3.8"

services:
  yolo-frontend:
    image: missnayomie/yolo-client:v1.0.0
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: yolo-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - yolo-backend
    networks:
      - mynetwork
    volumes:
      - ./client:/home/vagrant/YoloApp/client

  yolo-backend:
    image: missnayomie/yolo-backend:v1.0.0
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - mongodb
    networks:
      - mynetwork
    volumes:
      - ./backend:/home/vagrant/YoloApp/backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
      - type: volume
        source: mongodb_data
        target: /data/db

networks:
  mynetwork:
    name: mynetwork
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16 
          ip_range: 172.20.0.0/16 

volumes:
  mongodb_data:
    driver: local
