---
- name: Set up and run Yolo e-commerce app
  hosts: all
  become: true
  # vars:
  #   compose_file: "/home/vagrant/YoloApp/"
  tasks:
    - name: Load variables from file
      include_vars: vars/main.yml


  roles: 
    - docker
    - frontend
    - mongo
    - backend
