---
- name: Set up and run Yolo e-commerce app
  hosts: all
  become: true
  # vars:
  #   compose_file: "/home/vagrant/YoloApp/"
  vars_files:
    - vars/main.yml 


  roles: 
    - docker
    - frontend
    - mongo
    - backend