---
- name: Configure and deploy YoloApp
  hosts: localhost
  tasks:
    - name: Ensure the application directory exists
      ansible.builtin.file:
        path: /home/vagrant/YoloApp
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Deploy Docker Compose file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/roles/ansible_automation/files/docker-compose.yml"
        dest: "/home/vagrant/YoloApp/docker-compose.yml"

    - name: Start Docker Compose
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: /home/vagrant/YoloApp
