# roles/setup-mongodb/tasks/main.yml
---
- name: Pull MongoDB Docker image
  docker_image:
    name: mongo
    source: pull
  tags: mongodb

- name: Run MongoDB container
  docker_container:
    name: mongodb
    image: mongo
    state: started
    ports:
      - "27017:27017"
  tags: mongodb
