# roles/setup-mongodb/tasks/main.yml
---
- name: Run MongoDB container
  docker_container:
    name: mongodb
    image: mongo:latest
    networks:
      - mynetwork
    state: started
    volumes:
      - type: volume
        source: yoloapp_mongodb_data
        target: /data/db
    ports:
      - "27017:27017"
  tags: mongodb