# roles/setup-mongodb/tasks/main.yml
---
- name: Ensure mynetwork exists
  docker_network:
    name: mynetwork
    state: present

- name: Ensure MongoDB data volume exists
  docker_volume:
    name: mongodb_data
    state: present

- name: Run MongoDB container
  docker_container:
    name: mongodb
    image: mongo:latest
    state: started
    networks:
      - name: mynetwork
    volumes:
      - source: mongodb_data
        target: /data/db
        type: volume
    ports:
      - "27017:27017"
  tags: mongodb